/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group_assignment2;

import javax.swing.JOptionPane;

/**
 *
 * @author AVITA
 */
public class admin_main extends javax.swing.JFrame {
    private String userID;

    /**
     * Creates new form admin_menu
     */
    public admin_main(){
        
    }
    
    public admin_main(String userID) {
        initComponents();
        this.userID = userID;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_registerUsers = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        lblCompany = new javax.swing.JLabel();
        lblAdminMainpage = new javax.swing.JLabel();
        btnSM = new javax.swing.JButton();
        btnPM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_registerUsers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_registerUsers.setText("Register Users");
        btn_registerUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerUsersActionPerformed(evt);
            }
        });

        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_logout.setText("Log Out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        lblCompany.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCompany.setText("SIGMA SDN BHD");

        lblAdminMainpage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdminMainpage.setText("Administrator Main Menu");

        btnSM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSM.setText("Sales Manager Main Menu");
        btnSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSMActionPerformed(evt);
            }
        });

        btnPM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPM.setText("Purchase Manager Main Menu");
        btnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblCompany))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblAdminMainpage, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_registerUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblCompany)
                .addGap(12, 12, 12)
                .addComponent(lblAdminMainpage)
                .addGap(18, 18, 18)
                .addComponent(btn_registerUsers)
                .addGap(18, 18, 18)
                .addComponent(btnSM)
                .addGap(18, 18, 18)
                .addComponent(btnPM)
                .addGap(18, 18, 18)
                .addComponent(btn_logout)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Confirm to Log Out from system?" , "User Log Out Confirmation", JOptionPane.YES_NO_OPTION);
            
        if(choice == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Goodbye User!" , "See You Again", JOptionPane.INFORMATION_MESSAGE);
            log_in_page page1 = new log_in_page();
            page1.setVisible(true);

            dispose(); 
        } else{
            JOptionPane.showMessageDialog(null, "Not Logged Out" , "Purchase Manager Main Menu", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_registerUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerUsersActionPerformed
        admin_register_page arp = new admin_register_page();
        arp.setVisible(true);
        arp.setDefaultCloseOperation(log_in_page.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_btn_registerUsersActionPerformed

    private void btnSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSMActionPerformed
        SM_MainPage smm = new SM_MainPage(userID);
        smm.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnSMActionPerformed

    private void btnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMActionPerformed
        PM_MainPage pmm = new PM_MainPage();
        pmm.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnPMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new admin_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPM;
    private javax.swing.JButton btnSM;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_registerUsers;
    private javax.swing.JLabel lblAdminMainpage;
    private javax.swing.JLabel lblCompany;
    // End of variables declaration//GEN-END:variables
}
