package group_assignment2;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Renee Hiew
 */
public class PM_MainPage extends javax.swing.JFrame {

    /**
     * Creates new form PM_MainPage
     */
    public PM_MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPM_Mainpage = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        btnItems_List = new javax.swing.JButton();
        btnSupplier_List = new javax.swing.JButton();
        btnDisplay_requition = new javax.swing.JButton();
        btnPO = new javax.swing.JButton();
        btnPO_List = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPM_Mainpage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPM_Mainpage.setText("Purchase Manager Main Menu");

        lblCompany.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCompany.setText("SIGMA SDN BHD");

        btnItems_List.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnItems_List.setText("View Items Entry ");
        btnItems_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItems_ListActionPerformed(evt);
            }
        });

        btnSupplier_List.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSupplier_List.setText("View Suppliers List");
        btnSupplier_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplier_ListActionPerformed(evt);
            }
        });

        btnDisplay_requition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDisplay_requition.setText("View Purchase Requition");
        btnDisplay_requition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplay_requitionActionPerformed(evt);
            }
        });

        btnPO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPO.setText("Purchase Order Menu");
        btnPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPOActionPerformed(evt);
            }
        });

        btnPO_List.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPO_List.setText("View Purchase Orders List");
        btnPO_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPO_ListActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblPM_Mainpage))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPO_List, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnItems_List, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSupplier_List, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDisplay_requition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCompany)
                        .addGap(115, 115, 115))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPM_Mainpage)
                .addGap(18, 18, 18)
                .addComponent(btnItems_List)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSupplier_List)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisplay_requition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPO_List)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogOut)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnItems_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItems_ListActionPerformed
        ViewItemEntry vie = new ViewItemEntry();
        vie.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnItems_ListActionPerformed

    private void btnPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPOActionPerformed

        PO_MainMenu pmm = new PO_MainMenu();
        pmm.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnPOActionPerformed

    private void btnPO_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPO_ListActionPerformed
        
        ViewPO vpo = new ViewPO();
        vpo.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnPO_ListActionPerformed

    private void btnSupplier_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplier_ListActionPerformed
        ViewSuppliers vs = new ViewSuppliers();
        vs.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnSupplier_ListActionPerformed

    private void btnDisplay_requitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplay_requitionActionPerformed
        ViewRequisition vr = new ViewRequisition();
        vr.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnDisplay_requitionActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
 
        int choice = JOptionPane.showConfirmDialog(null, "Confirm to Log Out from system?" , "User Log Out Confirmation", JOptionPane.YES_NO_OPTION);
            
        if(choice == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Goodbye User!" , "See You Again", JOptionPane.INFORMATION_MESSAGE);
            log_in_page loginPage = new log_in_page();
            loginPage.setVisible(true);

            dispose(); 
        } else{
            JOptionPane.showMessageDialog(null, "Not Logged Out" , "Purchase Manager Main Menu", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplay_requition;
    private javax.swing.JButton btnItems_List;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPO;
    private javax.swing.JButton btnPO_List;
    private javax.swing.JButton btnSupplier_List;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblPM_Mainpage;
    // End of variables declaration//GEN-END:variables
}
