package group_assignment2;


import java.io.IOException;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Renee Hiew
 */
public class PO_MainMenu extends javax.swing.JFrame {

    private DefaultTableModel model = new DefaultTableModel();
    private int row = -1;
    /**
     * Creates new form PO_MainMenu
     */
    public PO_MainMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Purchase_Order_Main_Menu = new javax.swing.JTabbedPane();
        add_PO = new javax.swing.JPanel();
        addPage = new javax.swing.JPanel();
        lblPurchaseCart = new javax.swing.JLabel();
        lblPO = new javax.swing.JLabel();
        lblComName = new javax.swing.JLabel();
        lblPurID = new javax.swing.JLabel();
        txtPurID = new javax.swing.JTextField();
        lblNeededby = new javax.swing.JLabel();
        txtNeededBy = new javax.swing.JTextField();
        lblPOid = new javax.swing.JLabel();
        txtPOid = new javax.swing.JTextField();
        lblReq = new javax.swing.JLabel();
        txtReq = new javax.swing.JTextField();
        btnViewItems = new javax.swing.JButton();
        lblIns = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItem = new javax.swing.JTable();
        lblItemCode = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        lblItemName = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        lblUnitPrice = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnAddOrderList = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbOrders = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        lblTotalPur = new javax.swing.JLabel();
        txtTotalPur = new javax.swing.JTextField();
        lbltax = new javax.swing.JLabel();
        txtTax = new javax.swing.JTextField();
        lblTotalAmount = new javax.swing.JLabel();
        txtTotalAmt = new javax.swing.JTextField();
        btnDelItem = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnMainMenu1 = new javax.swing.JButton();
        lblInfoWarning = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        del_PO = new javax.swing.JPanel();
        delPage = new javax.swing.JPanel();
        lblDelPO = new javax.swing.JLabel();
        lblComName1 = new javax.swing.JLabel();
        lblEnterPO = new javax.swing.JLabel();
        txtPO_id = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDelPO = new javax.swing.JButton();
        btnMainMenu2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbPOdel = new javax.swing.JTable();
        edit_PO = new javax.swing.JPanel();
        lblEditPO = new javax.swing.JLabel();
        lblComName2 = new javax.swing.JLabel();
        lblSearchPO = new javax.swing.JLabel();
        txtPOID = new javax.swing.JTextField();
        btnSearchPO = new javax.swing.JButton();
        lblpurID = new javax.swing.JLabel();
        txtpurID = new javax.swing.JTextField();
        lblneededBY = new javax.swing.JLabel();
        txtneededBY = new javax.swing.JTextField();
        lblReq1 = new javax.swing.JLabel();
        txtReq1 = new javax.swing.JTextField();
        btnMainMenu3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblItemCode1 = new javax.swing.JLabel();
        txtItemCode1 = new javax.swing.JTextField();
        lblItemName1 = new javax.swing.JLabel();
        txtItemName1 = new javax.swing.JTextField();
        lblUnitPrice1 = new javax.swing.JLabel();
        txtUnitPrice1 = new javax.swing.JTextField();
        lblQuantity1 = new javax.swing.JLabel();
        txtQuantity1 = new javax.swing.JTextField();
        txtTotal1 = new javax.swing.JTextField();
        lblTotal1 = new javax.swing.JLabel();
        lblTotalPur1 = new javax.swing.JLabel();
        txtTotalPur1 = new javax.swing.JTextField();
        lbltax1 = new javax.swing.JLabel();
        txtTax1 = new javax.swing.JTextField();
        lblTotalAmount1 = new javax.swing.JLabel();
        txtTotalAmt1 = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCancelUpdate = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbPO = new javax.swing.JTable();
        lblInfo = new javax.swing.JLabel();
        lbl_POID = new javax.swing.JLabel();
        txt_POID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbItemEntry = new javax.swing.JTable();
        btnViewItemEntry = new javax.swing.JButton();
        lblInfo2 = new javax.swing.JLabel();
        lblinfo3 = new javax.swing.JLabel();
        btnEnter1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPurchaseCart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPurchaseCart.setText("Purchase Cart:");

        lblPO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPO.setText("PURCHASE ORDER");

        lblComName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblComName.setText("SIGMA SDN BHD");

        lblPurID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPurID.setText("Purchaser ID:");

        lblNeededby.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNeededby.setText("Needed By:");

        lblPOid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPOid.setText("Purchase Order ID: ");

        txtPOid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPOidActionPerformed(evt);
            }
        });

        lblReq.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReq.setText("Requisition ID:");

        txtReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReqActionPerformed(evt);
            }
        });

        btnViewItems.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewItems.setText("View Item Entry");
        btnViewItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewItemsActionPerformed(evt);
            }
        });

        lblIns.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIns.setText("Click button to view Item Entry:");

        tbItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItemMouseClicked(evt);
            }
        });
        tbItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbItemKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbItem);

        lblItemCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemCode.setText("Item Code:");

        lblItemName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemName.setText("Item Name:");

        lblUnitPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnitPrice.setText("Unit Price: ");

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantity.setText("Quantity: ");

        btnEnter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setText("Total: ");

        btnAddOrderList.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddOrderList.setText("Add To Order List");
        btnAddOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderListActionPerformed(evt);
            }
        });

        tbOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Unit Price", "Quantity", "Total Price"
            }
        ));
        jScrollPane3.setViewportView(tbOrders);

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Save Purchase Order");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblTotalPur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalPur.setText("Sub Total:");

        lbltax.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbltax.setText("Sales Tax:");

        lblTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalAmount.setText("Total Amount:");

        btnDelItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelItem.setText("Delete Item");
        btnDelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelItemActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnMainMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMainMenu1.setText("Main Menu");
        btnMainMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenu1ActionPerformed(evt);
            }
        });

        lblInfoWarning.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfoWarning.setForeground(new java.awt.Color(255, 51, 51));
        lblInfoWarning.setText("* Kindly make sure all details is according to the Purchase Requisition *");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("* Needed By format must be in dd-mm-yyyy *");

        javax.swing.GroupLayout addPageLayout = new javax.swing.GroupLayout(addPage);
        addPage.setLayout(addPageLayout);
        addPageLayout.setHorizontalGroup(
            addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPageLayout.createSequentialGroup()
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPageLayout.createSequentialGroup()
                                .addComponent(lblPO)
                                .addGap(18, 18, 18)
                                .addComponent(lblInfoWarning)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(addPageLayout.createSequentialGroup()
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPurID)
                                    .addComponent(lblNeededby))
                                .addGap(18, 18, 18)
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNeededBy)
                                    .addComponent(txtPurID, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblReq, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPOid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReq)
                                    .addComponent(txtPOid))))
                        .addGap(255, 255, 255)
                        .addComponent(btnMainMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPageLayout.createSequentialGroup()
                                .addComponent(lblIns)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnViewItems))
                            .addGroup(addPageLayout.createSequentialGroup()
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblItemCode)
                                    .addComponent(lblItemName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtItemName)
                                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPageLayout.createSequentialGroup()
                                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblQuantity)
                                            .addComponent(lblTotal))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEnter)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(addPageLayout.createSequentialGroup()
                                        .addComponent(btnAddOrderList, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancel))
                                    .addGroup(addPageLayout.createSequentialGroup()
                                        .addComponent(lblUnitPrice)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPageLayout.createSequentialGroup()
                                        .addComponent(btnDelItem)
                                        .addGap(131, 131, 131)
                                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(addPageLayout.createSequentialGroup()
                                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lbltax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblTotalPur))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtTax)
                                                    .addComponent(txtTotalPur)))
                                            .addGroup(addPageLayout.createSequentialGroup()
                                                .addComponent(lblTotalAmount)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtTotalAmt)))))
                                    .addGroup(addPageLayout.createSequentialGroup()
                                        .addGap(0, 2, Short.MAX_VALUE)
                                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblPurchaseCart)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblComName, javax.swing.GroupLayout.Alignment.TRAILING))))))))
                .addGap(112, 112, 112))
            .addGroup(addPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addPageLayout.setVerticalGroup(
            addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPageLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPO)
                    .addComponent(lblComName)
                    .addComponent(lblInfoWarning))
                .addGap(18, 18, 18)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPurID)
                            .addComponent(txtPurID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNeededby)
                            .addComponent(txtNeededBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPOid)
                            .addComponent(txtPOid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblReq)
                            .addComponent(txtReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnMainMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewItems, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIns)
                    .addComponent(lblPurchaseCart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPageLayout.createSequentialGroup()
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblItemCode)
                                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItemName)))
                            .addGroup(addPageLayout.createSequentialGroup()
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblUnitPrice)
                                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblQuantity)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddOrderList, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPur)
                            .addComponent(txtTotalPur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltax)
                            .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalAmount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout add_POLayout = new javax.swing.GroupLayout(add_PO);
        add_PO.setLayout(add_POLayout);
        add_POLayout.setHorizontalGroup(
            add_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_POLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        add_POLayout.setVerticalGroup(
            add_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_POLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Purchase_Order_Main_Menu.addTab("Add Purchase Order", add_PO);

        lblDelPO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDelPO.setText("Delete Purchase Order");

        lblComName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblComName1.setText("SIGMA SDN BHD");

        lblEnterPO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEnterPO.setText("Enter Purchase Order ID:");

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelPO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelPO.setText("Delete Purchase Order");
        btnDelPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelPOActionPerformed(evt);
            }
        });

        btnMainMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMainMenu2.setText("Main Menu");
        btnMainMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenu2ActionPerformed(evt);
            }
        });

        tbPOdel.setModel(model);
        jScrollPane5.setViewportView(tbPOdel);

        javax.swing.GroupLayout delPageLayout = new javax.swing.GroupLayout(delPage);
        delPage.setLayout(delPageLayout);
        delPageLayout.setHorizontalGroup(
            delPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delPageLayout.createSequentialGroup()
                .addGroup(delPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDelPO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblComName1))
                    .addGroup(delPageLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblEnterPO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPO_id, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMainMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delPageLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(delPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelPO, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        delPageLayout.setVerticalGroup(
            delPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delPageLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(delPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDelPO)
                    .addComponent(lblComName1))
                .addGap(21, 21, 21)
                .addGroup(delPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterPO)
                    .addComponent(txtPO_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnMainMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelPO, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );

        javax.swing.GroupLayout del_POLayout = new javax.swing.GroupLayout(del_PO);
        del_PO.setLayout(del_POLayout);
        del_POLayout.setHorizontalGroup(
            del_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(delPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        del_POLayout.setVerticalGroup(
            del_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(delPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Purchase_Order_Main_Menu.addTab("Delete Purchase Order", del_PO);

        lblEditPO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEditPO.setText("Edit Purchase Order");

        lblComName2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblComName2.setText("SIGMA SDN BHD");

        lblSearchPO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearchPO.setText("Search Purchase Order ID: ");

        btnSearchPO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchPO.setText("Search");
        btnSearchPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPOActionPerformed(evt);
            }
        });

        lblpurID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblpurID.setText("Purchaser ID:");

        lblneededBY.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblneededBY.setText("Needed By:");

        lblReq1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReq1.setText("Requisition ID: ");

        txtReq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReq1ActionPerformed(evt);
            }
        });

        btnMainMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMainMenu3.setText("Main Menu");
        btnMainMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenu3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Purchase Order: ");

        lblItemCode1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemCode1.setText("Item Code:");

        lblItemName1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemName1.setText("Item Name:");

        lblUnitPrice1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnitPrice1.setText("Unit Price: ");

        lblQuantity1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantity1.setText("Quantity: ");

        lblTotal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal1.setText("Total: ");

        lblTotalPur1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalPur1.setText("Sub Total:");

        lbltax1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbltax1.setText("Sales Tax:");

        lblTotalAmount1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalAmount1.setText("Total Amount:");

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Update Purchase Order");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Update Purchase Order Details: ");

        btnCancelUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelUpdate.setText("Cancel");
        btnCancelUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelUpdateActionPerformed(evt);
            }
        });

        tbPO.setModel(model);
        tbPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbPOMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbPOMouseReleased(evt);
            }
        });
        jScrollPane7.setViewportView(tbPO);

        lblInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 0, 51));
        lblInfo.setText("* Select the data row to edit *");

        lbl_POID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_POID.setText("Purchase Order ID: ");

        tbItemEntry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbItemEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbItemEntryMouseReleased(evt);
            }
        });
        tbItemEntry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbItemEntryKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbItemEntry);

        btnViewItemEntry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewItemEntry.setText("View Item Entry");
        btnViewItemEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewItemEntryActionPerformed(evt);
            }
        });

        lblInfo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfo2.setForeground(new java.awt.Color(255, 51, 51));
        lblInfo2.setText("* Click button to View item Entries *");

        lblinfo3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinfo3.setForeground(new java.awt.Color(255, 51, 51));
        lblinfo3.setText("* Select Item to Replace *");

        btnEnter1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnter1.setText("Enter");
        btnEnter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnter1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("* Needed By format must be in dd-mm-yyyy *");

        javax.swing.GroupLayout edit_POLayout = new javax.swing.GroupLayout(edit_PO);
        edit_PO.setLayout(edit_POLayout);
        edit_POLayout.setHorizontalGroup(
            edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_POLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(edit_POLayout.createSequentialGroup()
                        .addComponent(lblInfo2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(edit_POLayout.createSequentialGroup()
                        .addComponent(lblSearchPO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPOID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchPO)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(edit_POLayout.createSequentialGroup()
                        .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7)
                            .addGroup(edit_POLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(edit_POLayout.createSequentialGroup()
                                        .addComponent(lblEditPO)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblComName2))
                                    .addGroup(edit_POLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblInfo)
                                        .addGap(635, 635, 635)
                                        .addComponent(btnMainMenu3)))))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, edit_POLayout.createSequentialGroup()
                        .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(edit_POLayout.createSequentialGroup()
                                .addComponent(lbl_POID)
                                .addGap(18, 18, 18)
                                .addComponent(txt_POID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblReq1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReq1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(edit_POLayout.createSequentialGroup()
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblneededBY)
                                    .addComponent(lblpurID))
                                .addGap(48, 48, 48)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtneededBY)
                                    .addComponent(txtpurID, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblItemCode1)
                                    .addComponent(lblItemName1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtItemCode1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(txtItemName1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_POLayout.createSequentialGroup()
                                .addComponent(btnViewItemEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(edit_POLayout.createSequentialGroup()
                                        .addComponent(lblUnitPrice1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUnitPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(edit_POLayout.createSequentialGroup()
                                        .addComponent(lblQuantity1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEnter1)
                                            .addComponent(txtQuantity1))))))
                        .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(edit_POLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblinfo3)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(192, 192, 192))
                            .addGroup(edit_POLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalPur1)
                                    .addComponent(lblTotal1))
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(edit_POLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_POLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(txtTotalPur1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(edit_POLayout.createSequentialGroup()
                                        .addComponent(lblTotalAmount1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(edit_POLayout.createSequentialGroup()
                                        .addComponent(lbltax1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)))
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTax1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(edit_POLayout.createSequentialGroup()
                                        .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnCancelUpdate)
                                            .addComponent(txtTotalAmt1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        edit_POLayout.setVerticalGroup(
            edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_POLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_POLayout.createSequentialGroup()
                        .addComponent(lblEditPO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearchPO)
                            .addComponent(txtPOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchPO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblInfo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(edit_POLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblComName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMainMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(edit_POLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(edit_POLayout.createSequentialGroup()
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_POID)
                                    .addComponent(txt_POID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReq1)
                                    .addComponent(txtReq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblpurID)
                                    .addComponent(txtpurID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblneededBY)
                                    .addComponent(txtneededBY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(edit_POLayout.createSequentialGroup()
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblItemCode1)
                                    .addComponent(txtItemCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtItemName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItemName1))))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnViewItemEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnitPrice1)
                            .addComponent(txtUnitPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(edit_POLayout.createSequentialGroup()
                        .addComponent(lblinfo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_POLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(edit_POLayout.createSequentialGroup()
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTotal1)
                                    .addComponent(txtTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTotalPur1)
                                    .addComponent(txtTotalPur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(edit_POLayout.createSequentialGroup()
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbltax1)
                                    .addComponent(txtTax1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTotalAmount1)
                                    .addComponent(txtTotalAmt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(edit_POLayout.createSequentialGroup()
                        .addGroup(edit_POLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInfo2)
                            .addComponent(lblQuantity1)
                            .addComponent(txtQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnter1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelUpdate)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        Purchase_Order_Main_Menu.addTab("Edit Purchase Order", edit_PO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Purchase_Order_Main_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Purchase_Order_Main_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPOidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPOidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPOidActionPerformed

    private void txtReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReqActionPerformed

    
    private void btnViewItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewItemsActionPerformed

        try {
            DefaultTableModel dtm = LoadItemEntry.loadItems();
            tbItem.setModel(dtm);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnViewItemsActionPerformed

    private void tbItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItemMouseClicked
        
        DefaultTableModel dtm = (DefaultTableModel)tbItem.getModel();
        int select = tbItem.getSelectedRow();
        
        txtItemCode.setText(dtm.getValueAt(select, 0).toString());
        txtItemName.setText(dtm.getValueAt(select, 1).toString());
        txtUnitPrice.setText(dtm.getValueAt(select, 2).toString());
        txtQuantity.setText("");
        
    }//GEN-LAST:event_tbItemMouseClicked

    private OrderList orl = new OrderList();
    
    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        
        if (txtQuantity.getText().isEmpty() || txtItemCode.getText().isEmpty() || txtItemName.getText().isEmpty() || txtUnitPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty field is detected for item entry details. " + "\nPlease make sure all item entry details are filled.", "Item Entry Detail Fields Detected Empty", JOptionPane.WARNING_MESSAGE);
            return;
        } else{
            String itemCode = txtItemCode.getText();
            String itemName = txtItemName.getText();
            double unitPrice = Double.parseDouble(txtUnitPrice.getText());
            int quantity = Integer.parseInt(txtQuantity.getText());
        
            CalculateTotal cal = new CalculateTotal(itemCode, itemName, unitPrice, quantity);
            double totalPrice = cal.totalPrice();

            txtTotal.setText(Double.toString(totalPrice));
        
            OrderItems obj1 = new OrderItems(itemCode, itemName, unitPrice, quantity, totalPrice);
            orl.addOrder(obj1);
//            System.out.println(orl.toString());
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnAddOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderListActionPerformed
        
        if (txtQuantity.getText().isEmpty() || txtItemCode.getText().isEmpty() || txtItemName.getText().isEmpty() || txtUnitPrice.getText().isEmpty() ||txtTotal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty field is detected for item entry details. " + "\nPlease make sure all item entry details are filled.", "Item Entry Detail Detected Empty", JOptionPane.WARNING_MESSAGE);
            return; 
        } else{
            DefaultTableModel dtm = (DefaultTableModel)tbOrders.getModel();
            OrderItems allOrders = orl.getOrders().get(orl.getOrders().size() -1);
        
            Object[] data = { allOrders.getItemCode(), allOrders.getItemName(), allOrders.getUnitPrice(), allOrders.getQuantity(), allOrders.gettotalPrice()};
        
            dtm.addRow(data);
        
            txtItemCode.setText("");
            txtItemName.setText("");
            txtUnitPrice.setText("");
            txtQuantity.setText("");
            txtTotal.setText("");
            tbItem.clearSelection();
        }
    }//GEN-LAST:event_btnAddOrderListActionPerformed

    private void btnDelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelItemActionPerformed
        
        DefaultTableModel dtm = (DefaultTableModel) tbOrders.getModel();
        int selectedRow = tbOrders.getSelectedRow();

        if (selectedRow >= 0) {
            dtm.removeRow(selectedRow);
            orl.getOrders().remove(selectedRow);
            tbOrders.clearSelection();
            txtTotalPur.setText("");
            txtTax.setText("");
            txtTotalAmt.setText("");
        } else{
            JOptionPane.showMessageDialog(this, "Please select an item to delete.", "No Item Selected", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDelItemActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String POid = txtPOid.getText();
        String PurID = txtPurID.getText();
        String Date = txtNeededBy.getText();
        String Req = txtReq.getText();
        
        List<OrderItems> listOrder = orl.getOrders();
        
        double sum = 0;
        for (OrderItems currentOrder : listOrder){
            sum += currentOrder.totalPrice();
        }

        CalculatePO cal1 = new CalculatePO();
        cal1.setSum(sum);
        txtTotalPur.setText(Double.toString(sum));
        txtTax.setText(Double.toString(cal1.calculateTotalTax()));
        txtTotalAmt.setText(Double.toString(cal1.calculateTotalAmount()));
        
        if (sum == 0 || cal1.calculateTotalTax() == 0 || cal1.calculateTotalAmount() == 0) {
            JOptionPane.showMessageDialog(null, "No item detected. Please enter the items to proceed check out", "Checkout Error", JOptionPane.ERROR_MESSAGE);

            listOrder.clear();
            DefaultTableModel dtm = (DefaultTableModel) tbOrders.getModel();
            dtm.setRowCount(0);
            txtTotalPur.setText("");
            txtTax.setText("");
            txtTotalAmt.setText("");
            return;
        }
        
        if (POid.length() != 6 || POid.isEmpty()|| PurID.length() != 4 || PurID.isEmpty() || Date.length() != 10 || Date.isEmpty() || Req.length() != 5 || Req.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please make sure all Purchase Order details is completed." + "\n* Purchase Order ID must be in 6 value *" + "\n* Date must be in 8 value *" + "\n* Purchaser ID must be in 4 value *" + "\n* Requisition ID must be in 5 value *", "Empty Field Deteacted", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StringBuilder orderData = new StringBuilder();
        for (OrderItems order : orl.getOrders()) {
            orderData.append("\n" + POid.toUpperCase()).append("/").append(PurID.toUpperCase()).append("/").append(Date.toUpperCase())
                     .append("/").append(Req.toUpperCase()).append("/").append(order.getItemCode()).append("/").append(order.getItemName()).append("/").append(order.getUnitPrice())
                     .append("/").append(order.getQuantity()).append("/").append(order.gettotalPrice())
                     .append("/").append(sum).append("/").append(cal1.calculateTotalTax()).append("/").append(cal1.calculateTotalAmount())
                     .append(System.lineSeparator());
        }
        
        String userFilepath = "C:\\Users\\60125\\Documents\\OODJ Group Assignment\\user_log.txt";
        writeFile verify = new writeFile(userFilepath);
        
        if (!verify.verifyPurID(PurID)){
            JOptionPane.showMessageDialog(null, "Purchaser ID not found. Please try again.", "Invalid Purchase Manager ID", JOptionPane.WARNING_MESSAGE);
        } else{
            String PRfilepath = "C:\\Users\\60125\\Documents\\OODJ Group Assignment\\purchaseRequisition.txt";
            writeFile verifyPR = new writeFile(PRfilepath);

            if (!verifyPR.verifyReq(Req)){
                JOptionPane.showMessageDialog(null, "Requisition ID not found. Please try again.", "Invalid Requisition ID", JOptionPane.WARNING_MESSAGE);
            } else{
                String filepath = "C:\\Users\\60125\\Documents\\OODJ Group Assignment\\purchaseOrder.txt";

                String printData = orderData.toString();
                writeFile write = new writeFile(filepath);

                    if (write.verifyPOid(POid)){
                        JOptionPane.showMessageDialog(null, "Purchase Order ID existed. Please check Purchase Order ID.", "Purchase Order ID exits", JOptionPane.WARNING_MESSAGE);
                    } else{
                            if(write.appendOrder(printData)){
                                txtItemCode.setText("");
                                txtItemName.setText("");
                                txtUnitPrice.setText("");
                                txtQuantity.setText("");
                                txtTotal.setText("");
                                tbItem.clearSelection();
                                orl.getOrders().clear();
                                tbOrders.clearSelection();
                                JOptionPane.showMessageDialog(null, "Purchase Order successfully saved.", "Save Purchase Order: " + POid.toUpperCase(), JOptionPane.INFORMATION_MESSAGE);
                            }else {
                                JOptionPane.showMessageDialog(null, "Purchase Order Failed to save.", "Purchase Order Error Detacted", JOptionPane.ERROR_MESSAGE);
                            }
                    }
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Discharge Changes?", "Discharge Item Entry", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Item Entry Discharged", "Discharge Action Successful", JOptionPane.INFORMATION_MESSAGE);
            txtItemCode.setText("");
            txtItemName.setText("");
            txtUnitPrice.setText("");
            txtQuantity.setText("");
            txtTotal.setText("");
            tbItem.clearSelection();
            orl.getOrders().clear();
        } else{
            JOptionPane.showMessageDialog(null, "Purchase Order Not Discharge", "Discharge Action Cancelled", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtReq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReq1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String searchPO = txtPO_id.getText().toUpperCase();
        if(searchPO.length() != 6 || searchPO.isEmpty()){
            JOptionPane.showMessageDialog(null, "Purchase Order ID must be in 6 values and make sure to enter Purchase Order ID. Please Try Again.", "Invalid Purchase Order ID or Empty Text Field Detacted", JOptionPane.ERROR_MESSAGE);
            txtPO_id.setText("");
        } else{
            model.setRowCount(0);
            searchPO PurchaseOrder = new searchPO();
            PurchaseOrder.searchPurchaseOrder(model, searchPO);
            txtPO_id.setText("");     
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDelPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelPOActionPerformed

        int selectedRow = tbPOdel.getSelectedRow();

        if (selectedRow >= 0) {
            String selectedPO = tbPOdel.getValueAt(selectedRow, 0).toString();
            String selectedPOItem = tbPOdel.getValueAt(selectedRow, 6).toString();
            int choice = JOptionPane.showConfirmDialog(null, "Kindly take not that data will be deleted permanently." + "\nDo you want to delete the data of the selected Purchase Order?", "Delete Purchase Order Confirmation", JOptionPane.YES_NO_OPTION);
            
            if(choice == JOptionPane.YES_OPTION){
                model.removeRow(selectedRow);
                deleteFile del = new deleteFile();
                deleteFile.deletePO(selectedPO, selectedPOItem);
                JOptionPane.showMessageDialog(null, "Purchase Order data deleted.","Deleted Purchase Order Data", JOptionPane.INFORMATION_MESSAGE);
            } else{
                JOptionPane.showMessageDialog(null, "Delete Purchase Order discharged, no data deleted.", "Discharge Delete Purchase Order", JOptionPane.INFORMATION_MESSAGE);
            }
        } else{
            JOptionPane.showMessageDialog(this, "Please select an item to delete.", "No Item Selected", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDelPOActionPerformed
    
    private void btnSearchPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPOActionPerformed
        
        String searchPO = txtPOID.getText().toUpperCase();
        
        if(searchPO.length() != 6 || searchPO.isEmpty()){
            JOptionPane.showMessageDialog(null, "Purchase Order ID must be in 6 values and make sure to enter Purchase Order ID. Please Try Again.", "Invalid Purchase Order ID or empty text field detacted", JOptionPane.ERROR_MESSAGE);
            txtPOID.setText(""); 
        } else {
            model.setRowCount(0);
            searchPO PurchaseOrder = new searchPO();
            PurchaseOrder.searchPurchaseOrder(model, searchPO);
            txtPOID.setText(""); 
            txt_POID.setText("");
            txtpurID.setText("");
            txtneededBY.setText("");
            txtReq1.setText(""); 
        }
        
    }//GEN-LAST:event_btnSearchPOActionPerformed

    private void btnMainMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenu1ActionPerformed
        PM_MainPage pmm = new PM_MainPage();
        pmm.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnMainMenu1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        String poid1 = txt_POID.getText();
        String Purid1 = txtpurID.getText();
        String Date1 = txtneededBY.getText();
        String Req1 = txtReq1.getText();
        List<OrderItems> listOrder2 = orl2.getOrders();
        
        double sum = 0;
        for (OrderItems currentOrder2 : listOrder2){
            sum += currentOrder2.totalPrice();
        }

        CalculatePO cal2 = new CalculatePO();
        cal2.setSum(sum);
        txtTotalPur1.setText(Double.toString(sum));
        txtTax1.setText(Double.toString(cal2.calculateTotalTax()));
        txtTotalAmt1.setText(Double.toString(cal2.calculateTotalAmount()));
//        System.out.println(orl2.toString());
        
        if (sum == 0 || cal2.calculateTotalTax() == 0 || cal2.calculateTotalAmount() == 0) {
            JOptionPane.showMessageDialog(null, "No item detected. Please enter the items to proceed check out", "Checkout Error", JOptionPane.ERROR_MESSAGE);
            txtTotalPur1.setText("");
            txtTax1.setText("");
            txtTotalAmt1.setText("");
            return;
        }
        
        if (poid1.length() != 6 || poid1.isEmpty()|| Purid1.isEmpty() || Date1.isEmpty() || Req1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please make sure all Purchase Order details is completed." + "\n* Purchase Order ID must be in 6 value *", "Empty Field Deteacted", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int selectedRow = tbPO.getSelectedRow();
        
        if (selectedRow >= 0) {
            String selectedPO = tbPO.getValueAt(selectedRow, 0).toString();
            String selectedPOItem = tbPO.getValueAt(selectedRow, 6).toString();
            
            model.removeRow(selectedRow);
            
            deleteFile del = new deleteFile();
            deleteFile.deletePO(selectedPO, selectedPOItem);
            
        } else{
            JOptionPane.showMessageDialog(this, "Please select a Purchase Order to update.", "No Item Selected", JOptionPane.WARNING_MESSAGE);
        }
        
        StringBuilder orderData = new StringBuilder();
        for (OrderItems order : orl2.getOrders()) {
                orderData.append("\n" + poid1.toUpperCase()).append("/").append(Purid1.toUpperCase()).append("/").append(Date1.toUpperCase())
                        .append("/").append(Req1.toUpperCase())
                        .append("/").append(order.getItemCode()).append("/").append(order.getItemName()).append("/").append(order.getUnitPrice())
                        .append("/").append(order.getQuantity()).append("/").append(order.gettotalPrice())
                        .append("/").append(sum).append("/").append(cal2.calculateTotalTax()).append("/").append(cal2.calculateTotalAmount())
                        .append(System.lineSeparator());
        }
        
        String filepath = "C:\\Users\\60125\\Documents\\OODJ Group Assignment\\purchaseOrder.txt";
        String updateData = orderData.toString();
        
        writeFile write = new writeFile(filepath);
        if(write.appendOrder(updateData)){
            JOptionPane.showMessageDialog(null, "Purchase Order successfully saved.", "Save Purchase Order: " + poid1, JOptionPane.INFORMATION_MESSAGE);
            txt_POID.setText("");
            txtpurID.setText("");
            txtneededBY.setText("");
            txtReq1.setText("");
            txtItemCode1.setText("");
            txtItemName1.setText("");
            txtUnitPrice1.setText("");
            txtQuantity1.setText("");
            txtTotal1.setText("");
            orl2.getOrders().clear();
            tbItemEntry.clearSelection();
            tbPO.clearSelection();
            txtTotalPur1.setText("");
            txtTax1.setText("");
            txtTotalAmt1.setText("");
        }else {
            JOptionPane.showMessageDialog(null, "Purchase Order Failed to save.", "Purchase Order Error Detacted", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelUpdateActionPerformed
        
        int choice = JOptionPane.showConfirmDialog(null, "Discharge Changes?", "Cancel Update", JOptionPane.YES_NO_OPTION);
        
        if(choice == JOptionPane.YES_OPTION){
            model.setRowCount(0);
            txt_POID.setText("");
            txtpurID.setText("");
            txtneededBY.setText("");
            txtReq1.setText("");
            txtItemCode1.setText("");
            txtItemName1.setText("");
            txtUnitPrice1.setText("");
            txtQuantity1.setText("");
            txtTotal1.setText("");
            txtTotalPur1.setText("");
            txtTax1.setText("");
            txtTotalAmt1.setText("");
            tbItemEntry.clearSelection();
            orl2.getOrders().clear();
        }else{
            JOptionPane.showMessageDialog(null, "Purchase Order Edit Failed.", "Purchase Order Not Edited", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelUpdateActionPerformed

    private void tbPOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPOMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tbPOMouseExited

    private void tbPOMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPOMouseReleased

        row = tbPO.getSelectedRow();
        
        String poID = String.valueOf(model.getValueAt(row, 0));
        String purId = String.valueOf(model.getValueAt(row, 1));
        String date = String.valueOf(model.getValueAt(row, 2));
        String req = String.valueOf(model.getValueAt(row, 3));
        String itemCode = String.valueOf(model.getValueAt(row, 4));
        String itemName = String.valueOf(model.getValueAt(row, 5));
        String unitPrice = String.valueOf(model.getValueAt(row, 6));
        String quantity = String.valueOf(model.getValueAt(row, 7));
        String totalPrice = String.valueOf(model.getValueAt(row, 8));
        String subTotal = String.valueOf(model.getValueAt(row, 9));
        String salesTax = String.valueOf(model.getValueAt(row, 10));
        String totalAmt = String.valueOf(model.getValueAt(row, 11));
        
        txt_POID.setText(poID);
        txtpurID.setText(purId);
        txtneededBY.setText(date);
        txtReq1.setText(req);
        txtItemCode1.setText(itemCode);
        txtItemName1.setText(itemName);
        txtUnitPrice1.setText(unitPrice);
        txtQuantity1.setText(quantity);
        txtTotal1.setText(totalPrice);
        txtTotalPur1.setText(subTotal);
        txtTax1.setText(salesTax);
        txtTotalAmt1.setText(totalAmt);
    }//GEN-LAST:event_tbPOMouseReleased

    private void btnMainMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenu2ActionPerformed
        PM_MainPage pmm = new PM_MainPage();
        pmm.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnMainMenu2ActionPerformed

    private void btnMainMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenu3ActionPerformed
        PM_MainPage pmm = new PM_MainPage();
        pmm.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnMainMenu3ActionPerformed

    private void btnViewItemEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewItemEntryActionPerformed
        try {
            DefaultTableModel dtm = LoadItemEntry.loadItems();
            tbItemEntry.setModel(dtm);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnViewItemEntryActionPerformed

    private void tbItemEntryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItemEntryMouseReleased
        
        DefaultTableModel dtm = (DefaultTableModel)tbItemEntry.getModel();
        int select = tbItemEntry.getSelectedRow();
        
        txtItemCode1.setText(dtm.getValueAt(select, 0).toString());
        txtItemName1.setText(dtm.getValueAt(select, 1).toString());
        txtUnitPrice1.setText(dtm.getValueAt(select, 2).toString());
        txtQuantity1.setText("");
        txtTotal1.setText("");
        txtTotalPur1.setText("");
        txtTax1.setText("");
        txtTotalAmt1.setText("");
        
    }//GEN-LAST:event_tbItemEntryMouseReleased

    private void tbItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbItemKeyReleased
       
    }//GEN-LAST:event_tbItemKeyReleased

    private void tbItemEntryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbItemEntryKeyReleased
        DefaultTableModel dtm1 = (DefaultTableModel)tbItemEntry.getModel();
        int select = tbItemEntry.getSelectedRow();
        
        String itemCode = String.valueOf(dtm1.getValueAt(row, 6));
        String itemName = String.valueOf(dtm1.getValueAt(row, 7));
        String unitPrice = String.valueOf(dtm1.getValueAt(row, 8));
        
        txtItemCode1.setText(itemCode);
        txtItemName1.setText(itemName);
        txtUnitPrice1.setText(unitPrice);
        txtQuantity1.setText("");
        txtTotal1.setText("");
        txtTotalPur1.setText("");
        txtTax1.setText("");
        txtTotalAmt1.setText("");
    }//GEN-LAST:event_tbItemEntryKeyReleased

    private OrderList orl2 = new OrderList();
    
    private void btnEnter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnter1ActionPerformed
        
        if (txtQuantity1.getText().isEmpty() || txtItemCode1.getText().isEmpty() || txtItemName1.getText().isEmpty() || txtUnitPrice1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty field is detected for item entry details. " + "\nPlease make sure all item entry details are filled.", "Item Entry Detail Fields Detected Empty", JOptionPane.WARNING_MESSAGE);
            return;
        } else{
            String itemCode1 = txtItemCode1.getText();
            String itemName1 = txtItemName1.getText();
            double unitPrice1 = Double.parseDouble(txtUnitPrice1.getText());
            int quantity1 = Integer.parseInt(txtQuantity1.getText());
        
            CalculateTotal cal = new CalculateTotal(itemCode1, itemName1, unitPrice1, quantity1);
            double totalPrice1 = cal.totalPrice();

            txtTotal1.setText(Double.toString(totalPrice1));
        
            OrderItems obj1 = new OrderItems(itemCode1, itemName1, unitPrice1, quantity1, totalPrice1);
            orl2.addOrder(obj1);
        }
    }//GEN-LAST:event_btnEnter1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PO_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PO_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PO_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PO_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PO_MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Purchase_Order_Main_Menu;
    private javax.swing.JPanel addPage;
    private javax.swing.JPanel add_PO;
    private javax.swing.JButton btnAddOrderList;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelUpdate;
    private javax.swing.JButton btnDelItem;
    private javax.swing.JButton btnDelPO;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnEnter1;
    private javax.swing.JButton btnMainMenu1;
    private javax.swing.JButton btnMainMenu2;
    private javax.swing.JButton btnMainMenu3;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchPO;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewItemEntry;
    private javax.swing.JButton btnViewItems;
    private javax.swing.JPanel delPage;
    private javax.swing.JPanel del_PO;
    private javax.swing.JPanel edit_PO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblComName;
    private javax.swing.JLabel lblComName1;
    private javax.swing.JLabel lblComName2;
    private javax.swing.JLabel lblDelPO;
    private javax.swing.JLabel lblEditPO;
    private javax.swing.JLabel lblEnterPO;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblInfoWarning;
    private javax.swing.JLabel lblIns;
    private javax.swing.JLabel lblItemCode;
    private javax.swing.JLabel lblItemCode1;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemName1;
    private javax.swing.JLabel lblNeededby;
    private javax.swing.JLabel lblPO;
    private javax.swing.JLabel lblPOid;
    private javax.swing.JLabel lblPurID;
    private javax.swing.JLabel lblPurchaseCart;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblQuantity1;
    private javax.swing.JLabel lblReq;
    private javax.swing.JLabel lblReq1;
    private javax.swing.JLabel lblSearchPO;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblTotalAmount1;
    private javax.swing.JLabel lblTotalPur;
    private javax.swing.JLabel lblTotalPur1;
    private javax.swing.JLabel lblUnitPrice;
    private javax.swing.JLabel lblUnitPrice1;
    private javax.swing.JLabel lbl_POID;
    private javax.swing.JLabel lblinfo3;
    private javax.swing.JLabel lblneededBY;
    private javax.swing.JLabel lblpurID;
    private javax.swing.JLabel lbltax;
    private javax.swing.JLabel lbltax1;
    private javax.swing.JTable tbItem;
    private javax.swing.JTable tbItemEntry;
    private javax.swing.JTable tbOrders;
    private javax.swing.JTable tbPO;
    private javax.swing.JTable tbPOdel;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemCode1;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemName1;
    private javax.swing.JTextField txtNeededBy;
    private javax.swing.JTextField txtPOID;
    private javax.swing.JTextField txtPO_id;
    private javax.swing.JTextField txtPOid;
    private javax.swing.JTextField txtPurID;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtQuantity1;
    private javax.swing.JTextField txtReq;
    private javax.swing.JTextField txtReq1;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTax1;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotal1;
    private javax.swing.JTextField txtTotalAmt;
    private javax.swing.JTextField txtTotalAmt1;
    private javax.swing.JTextField txtTotalPur;
    private javax.swing.JTextField txtTotalPur1;
    private javax.swing.JTextField txtUnitPrice;
    private javax.swing.JTextField txtUnitPrice1;
    private javax.swing.JTextField txt_POID;
    private javax.swing.JTextField txtneededBY;
    private javax.swing.JTextField txtpurID;
    // End of variables declaration//GEN-END:variables
}
