/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group_assignment2;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Renee Hiew
 */
public class SM_MainPage extends javax.swing.JFrame {
    String userID;

    /**
     * Creates new form SM_MainPage
     */
    public SM_MainPage (){
        initComponents();
    }
    
    public SM_MainPage(String userID) {
        initComponents();
        this.userID = userID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPM_Mainpage = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        btnItemEntry = new javax.swing.JButton();
        btnSupplierEntry = new javax.swing.JButton();
        btnDaily = new javax.swing.JButton();
        btnPRpage = new javax.swing.JButton();
        btnViewReq = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnViewPO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPM_Mainpage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPM_Mainpage.setText("Sales Manager Main Menu");

        lblCompany.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCompany.setText("SIGMA SDN BHD");

        btnItemEntry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnItemEntry.setText("Items Entry Page");
        btnItemEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemEntryActionPerformed(evt);
            }
        });

        btnSupplierEntry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSupplierEntry.setText("Supplier Entry Page");
        btnSupplierEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierEntryActionPerformed(evt);
            }
        });

        btnDaily.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDaily.setText("Daily Item - wise Sales Entry");
        btnDaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDailyActionPerformed(evt);
            }
        });

        btnPRpage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPRpage.setText("Purchase Requisition Page");
        btnPRpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPRpageActionPerformed(evt);
            }
        });

        btnViewReq.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewReq.setText("Display Requisition");
        btnViewReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReqActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnViewPO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewPO.setText("View Purchase Orders");
        btnViewPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(lblPM_Mainpage))
                        .addComponent(btnViewReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnItemEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSupplierEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDaily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPRpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addComponent(btnViewPO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCompany)
                        .addGap(48, 48, 48)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPM_Mainpage)
                .addGap(18, 18, 18)
                .addComponent(btnItemEntry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSupplierEntry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDaily)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPRpage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewReq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogOut)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnItemEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemEntryActionPerformed
        try {
            item_entry vie = new item_entry(userID);
            vie.setVisible(true);
            vie.setDefaultCloseOperation(log_in_page.DISPOSE_ON_CLOSE);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(SM_MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnItemEntryActionPerformed

    private void btnSupplierEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierEntryActionPerformed
        //problem
        try {
            supplier_entry spe = new supplier_entry(userID);
            spe.setVisible(true);
            spe.setDefaultCloseOperation(log_in_page.DISPOSE_ON_CLOSE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SM_MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnSupplierEntryActionPerformed

    private void btnDailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDailyActionPerformed
        try {
            daily_item_sales dis = new daily_item_sales(userID);
            dis.setVisible(true);
            dis.setDefaultCloseOperation(log_in_page.DISPOSE_ON_CLOSE);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(SM_MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnDailyActionPerformed

    private void btnPRpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPRpageActionPerformed

        try {
           new purchase_requisition(userID).setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SM_MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnPRpageActionPerformed

    private void btnViewReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReqActionPerformed
        display_requisition dr = new display_requisition(userID);
        dr.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnViewReqActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        int choice = JOptionPane.showConfirmDialog(null, "Confirm to Log Out from system?" , "User Log Out Confirmation", JOptionPane.YES_NO_OPTION);
            
        if(choice == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Goodbye User!" , "See You Again", JOptionPane.INFORMATION_MESSAGE);
            log_in_page loginPage = new log_in_page();
            loginPage.setVisible(true);

            dispose(); 
        } else{
            JOptionPane.showMessageDialog(null, "Not Logged Out" , "Purchase Manager Main Menu", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnViewPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPOActionPerformed
        view_purchase_order vpo = new view_purchase_order(userID);
        vpo.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnViewPOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SM_MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaily;
    private javax.swing.JButton btnItemEntry;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPRpage;
    private javax.swing.JButton btnSupplierEntry;
    private javax.swing.JButton btnViewPO;
    private javax.swing.JButton btnViewReq;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblPM_Mainpage;
    // End of variables declaration//GEN-END:variables
}
