package group_assignment2;


import group_assignment2.SupplierEntry;
import group_assignment2.item_entry;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AVITA
 */
public class supplier_entry extends javax.swing.JFrame {
    private DefaultTableModel seModel = new DefaultTableModel();
    private String[] seColumns = {"Supplier Code","Supplier Name","Item ID"};
    private String supplierEntriesFilePath = "C:\\Users\\60125\\Documents\\OODJ Group Assignment\\supplierEntry.txt";
    private String supplierEntriesTempFilePath = "C:\\Users\\60125\\Documents\\OODJ Group Assignment\\tempSupplierEntry.txt";
    private String header = "Supplier Code , Supplier Name , Item ID";
    private String userID;
    private int row = -1;
    private String[] itemIDs = {};

    /**
     * Creates new form supplier_entry
     * @throws java.io.FileNotFoundException
     */
    public supplier_entry() throws FileNotFoundException{
        initComponents();
        seModel.setColumnIdentifiers(seColumns);
                
        File sefile = new File(supplierEntriesFilePath);
        Scanner sc = new Scanner(sefile);
        
        if(sc.hasNextLine())sc.nextLine();
        
        while(sc.hasNextLine()){
            String rowSupplierEntries = sc.nextLine();
            String[] partsSupplierEntries = rowSupplierEntries.split("[/]+");
            seModel.addRow(partsSupplierEntries);
            itemIDs = Arrays.copyOf(itemIDs, itemIDs.length + 1);
            itemIDs [itemIDs.length - 1] = partsSupplierEntries[2];
        }
        sc.close();
    }
    
    public supplier_entry(String userID) throws FileNotFoundException {
        initComponents();
        seModel.setColumnIdentifiers(seColumns);
        
        this.userID = userID;
        
        File sefile = new File(supplierEntriesFilePath);
        Scanner sc = new Scanner(sefile);
        
        if(sc.hasNextLine())sc.nextLine();
        
        while(sc.hasNextLine()){
            String rowSupplierEntries = sc.nextLine();
            String[] partsSupplierEntries = rowSupplierEntries.split("[/]+");
            seModel.addRow(partsSupplierEntries);
            itemIDs = Arrays.copyOf(itemIDs, itemIDs.length + 1);
            itemIDs [itemIDs.length - 1] = partsSupplierEntries[2];
        }
        sc.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompany = new javax.swing.JLabel();
        lbl_supplierEntry = new javax.swing.JLabel();
        lbl_supplierCode = new javax.swing.JLabel();
        lbl_supplierName = new javax.swing.JLabel();
        lbl_itemID = new javax.swing.JLabel();
        txt_supplierCode = new javax.swing.JTextField();
        txt_supplierName = new javax.swing.JTextField();
        txt_itemID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_supplierEntry = new javax.swing.JTable();
        btn_addSupplierEntry = new javax.swing.JButton();
        btn_editSupplierEntry = new javax.swing.JButton();
        btn_dltSupplierEntry = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();
        lblCompany1 = new javax.swing.JLabel();

        lblCompany.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCompany.setText("SIGMA SDN BHD");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_supplierEntry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_supplierEntry.setText("Supplier Entry");

        lbl_supplierCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_supplierCode.setText("Supplier Code:");

        lbl_supplierName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_supplierName.setText("Supplier Name:");

        lbl_itemID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_itemID.setText("Item ID:");

        tbl_supplierEntry.setModel(seModel);
        tbl_supplierEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_supplierEntryMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_supplierEntry);

        btn_addSupplierEntry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_addSupplierEntry.setText("Add");
        btn_addSupplierEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addSupplierEntryActionPerformed(evt);
            }
        });

        btn_editSupplierEntry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_editSupplierEntry.setText("Edit");
        btn_editSupplierEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editSupplierEntryActionPerformed(evt);
            }
        });

        btn_dltSupplierEntry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_dltSupplierEntry.setText("Delete");
        btn_dltSupplierEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dltSupplierEntryActionPerformed(evt);
            }
        });

        btnMainMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        lblCompany1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCompany1.setText("SIGMA SDN BHD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_addSupplierEntry)
                        .addGap(46, 46, 46)
                        .addComponent(btn_editSupplierEntry)
                        .addGap(50, 50, 50)
                        .addComponent(btn_dltSupplierEntry)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMainMenu)
                        .addGap(80, 80, 80)
                        .addComponent(lblCompany1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_itemID)
                    .addComponent(lbl_supplierName)
                    .addComponent(lbl_supplierCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_supplierCode)
                    .addComponent(txt_supplierName)
                    .addComponent(txt_itemID, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_supplierEntry)
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMainMenu)
                    .addComponent(lblCompany1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_supplierEntry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_supplierCode)
                    .addComponent(txt_supplierCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_supplierName)
                    .addComponent(txt_supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_itemID)
                    .addComponent(txt_itemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addSupplierEntry)
                    .addComponent(btn_editSupplierEntry)
                    .addComponent(btn_dltSupplierEntry))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addSupplierEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addSupplierEntryActionPerformed
        // TODO add your handling code here:
        String supplierCode = txt_supplierCode.getText();
        String supplierName = txt_supplierName.getText();
        String itemID = txt_itemID.getText();
        
        boolean idDuplication = false;
        for (String ID : itemIDs){
            if(itemID.equals(ID)){
                idDuplication = true;
                break;
            }
            else{
                idDuplication = false;
            }
        }
        
        if(row>-1){
            JOptionPane.showMessageDialog(null, "Data existed. Please Try Again", "Data Record Found", JOptionPane.WARNING_MESSAGE);
            tbl_supplierEntry.getSelectionModel().clearSelection();
            row = -1;
            
            txt_supplierCode.setText("");
            txt_supplierName.setText("");
            txt_itemID.setText(""); 
        }
        else if("".equals(supplierCode) || "".equals(supplierName) || "".equals(itemID)){
            JOptionPane.showMessageDialog(null, "Please ensure all data are filled.", "Empty Fields Detacted", JOptionPane.WARNING_MESSAGE);
        }
        else{
            if(!idDuplication){
                try {
                String[] newSupplierEntry = {supplierCode,supplierName,itemID};
                seModel.addRow(newSupplierEntry); 
                
                txt_supplierCode.setText("");
                txt_supplierName.setText("");
                txt_itemID.setText(""); 
                
                SupplierEntry add = new SupplierEntry(newSupplierEntry, supplierEntriesFilePath);
                add.add();
                } catch (IOException ex) {
                    Logger.getLogger(item_entry.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Item ID already exist.");
            }
            
        }
    }//GEN-LAST:event_btn_addSupplierEntryActionPerformed

    private void btn_dltSupplierEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dltSupplierEntryActionPerformed
        // TODO add your handling code here:
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select data row to delete.", "No Item Selected", JOptionPane.WARNING_MESSAGE);
        }
        else{
            seModel.removeRow(row);
            tbl_supplierEntry.getSelectionModel().clearSelection();
            
            txt_supplierCode.setText("");
            txt_supplierName.setText("");
            txt_itemID.setText("");
            
            SupplierEntry dlt = new SupplierEntry(row, supplierEntriesFilePath, supplierEntriesTempFilePath, header);
            try {
                if (dlt.delete()){
                    JOptionPane.showMessageDialog(null, "Supplier Entry Deleted.","Successfully Deleted Supplier Entry", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error Deleting Selected Row", "Error Detacted", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(supplier_entry.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            row = -1;
        }
    }//GEN-LAST:event_btn_dltSupplierEntryActionPerformed

    private void btn_editSupplierEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editSupplierEntryActionPerformed

        if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select data row to edit.", "No Item Selected", JOptionPane.WARNING_MESSAGE);
        }
        else{
            String supplierCode = txt_supplierCode.getText();
            String supplierName = txt_supplierName.getText();
            String itemID = txt_itemID.getText();
            
            String[] newEdit = {supplierCode,supplierName,itemID};

            seModel.setValueAt(supplierCode, row, 0);
            seModel.setValueAt(supplierName, row, 1);
            seModel.setValueAt(itemID, row, 2);
            
            SupplierEntry edit = new SupplierEntry(row, newEdit, supplierEntriesFilePath, supplierEntriesTempFilePath, header);
            
            try {
                if (edit.edit()) JOptionPane.showMessageDialog(null, "Changes Made Saved.");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(item_entry.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(item_entry.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            tbl_supplierEntry.getSelectionModel().clearSelection();
            
            txt_supplierCode.setText("");
            txt_supplierName.setText("");
            txt_itemID.setText("");
            
            row = -1;
        }
    }//GEN-LAST:event_btn_editSupplierEntryActionPerformed

    private void tbl_supplierEntryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_supplierEntryMouseReleased
        // TODO add your handling code here:
        row = tbl_supplierEntry.getSelectedRow();
        String supplierCode = String.valueOf(seModel.getValueAt(row, 0));
        String supplierName = String.valueOf(seModel.getValueAt(row, 1));
        String itemID = String.valueOf(seModel.getValueAt(row, 2));
        
        txt_supplierCode.setText(supplierCode);
        txt_supplierName.setText(supplierName);
        txt_itemID.setText(itemID);
    }//GEN-LAST:event_tbl_supplierEntryMouseReleased

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        SM_MainPage mainPage = new SM_MainPage(userID);
        mainPage.setVisible(true);
        dispose();        
    }//GEN-LAST:event_btnMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new supplier_entry().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(supplier_entry.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btn_addSupplierEntry;
    private javax.swing.JButton btn_dltSupplierEntry;
    private javax.swing.JButton btn_editSupplierEntry;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblCompany1;
    private javax.swing.JLabel lbl_itemID;
    private javax.swing.JLabel lbl_supplierCode;
    private javax.swing.JLabel lbl_supplierEntry;
    private javax.swing.JLabel lbl_supplierName;
    private javax.swing.JTable tbl_supplierEntry;
    private javax.swing.JTextField txt_itemID;
    private javax.swing.JTextField txt_supplierCode;
    private javax.swing.JTextField txt_supplierName;
    // End of variables declaration//GEN-END:variables
}
